theme = "hex_steel"

[editor]
mouse = true
auto-format = true
auto-completion = true
path-completion = true
gutters = [
  "diagnostics",
  "spacer",
  "line-numbers",
  "spacer",
  "diff",
]
# rulers = [80]
clipboard-provider = "wayland"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

