[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.clangd]
command = "clangd"

[language-server.nasm-lsp]
command = "nasm-lsp"

[language-server.masm-lsp]
command = "masm-lsp"

[[language]]
name = "rust"
scope = "source.rust"
file-types = ["rs"]
language-servers = ["rust-analyzer"]

[[language]]
name = "python"
scope = "source.python"
file-types = ["py"]
language-servers = ["pyright"]

[[language]]
name = "c"
scope = "source.c"
file-types = ["c", "h"]
language-servers = ["clangd"]

[[language]]
name = "cpp"
scope = "source.cpp"
file-types = ["cpp", "hpp", "cc", "cxx"]
language-servers = ["clangd"]

[[language]]
name = "assembly"
scope = "source.assembly"
file-types = ["s", "asm"]
language-servers = ["nasm-lsp", "masm-lsp"]
