return {
  'zaldih/themery.nvim',
  lazy = false,
  priority = 998,
  keys = {
    { '<leader>ct', '<cmd>Themery<CR>', desc = '[C]olorscheme [T]heme picker' },
  },
  opts = {
    themes = {
      {
        name = 'Melange Dark',
        colorscheme = 'melange',
        before = [[vim.opt.background = "dark"]],
      },
      {
        name = 'Melange Light',
        colorscheme = 'melange',
        before = [[vim.opt.background = "light"]],
      },
      {
        name = 'Alabaster Dark',
        colorscheme = 'alabaster',
        before = [[vim.opt.background = "dark"]],
      },
      {
        name = 'Alabaster Light',
        colorscheme = 'alabaster',
        before = [[vim.opt.background = "light"]],
      },
      { name = 'blue',      colorscheme = 'blue',      before = [[vim.opt.background = "dark"]] },
      { name = 'darkblue',  colorscheme = 'darkblue',  before = [[vim.opt.background = "dark"]] },
      { name = 'default',   colorscheme = 'default',   before = [[vim.opt.background = "dark"]] },
      { name = 'delek',     colorscheme = 'delek',     before = [[vim.opt.background = "dark"]] },
      { name = 'desert',    colorscheme = 'desert',    before = [[vim.opt.background = "dark"]] },
      { name = 'elflord',   colorscheme = 'elflord',   before = [[vim.opt.background = "dark"]] },
      { name = 'evening',   colorscheme = 'evening',   before = [[vim.opt.background = "dark"]] },
      { name = 'habamax',   colorscheme = 'habamax',   before = [[vim.opt.background = "dark"]] },
      { name = 'industry',  colorscheme = 'industry',  before = [[vim.opt.background = "dark"]] },
      { name = 'koehler',   colorscheme = 'koehler',   before = [[vim.opt.background = "dark"]] },
      { name = 'lunaperche',colorscheme = 'lunaperche',before = [[vim.opt.background = "dark"]] },
      { name = 'morning',   colorscheme = 'morning',   before = [[vim.opt.background = "light"]] },
      { name = 'murphy',    colorscheme = 'murphy',    before = [[vim.opt.background = "dark"]] },
      { name = 'pablo',     colorscheme = 'pablo',     before = [[vim.opt.background = "dark"]] },
      { name = 'peachpuff', colorscheme = 'peachpuff', before = [[vim.opt.background = "light"]] },
      { name = 'quiet',     colorscheme = 'quiet',     before = [[vim.opt.background = "dark"]] },
      { name = 'retrobox',  colorscheme = 'retrobox',  before = [[vim.opt.background = "dark"]] },
      { name = 'ron',       colorscheme = 'ron',       before = [[vim.opt.background = "dark"]] },
      { name = 'shine',     colorscheme = 'shine',     before = [[vim.opt.background = "light"]] },
      { name = 'slate',     colorscheme = 'slate',     before = [[vim.opt.background = "dark"]] },
      { name = 'sorbet',    colorscheme = 'sorbet',    before = [[vim.opt.background = "dark"]] },
      { name = 'torte',     colorscheme = 'torte',     before = [[vim.opt.background = "dark"]] },
      { name = 'wildcharm', colorscheme = 'wildcharm', before = [[vim.opt.background = "dark"]] },
      { name = 'zaibatsu',  colorscheme = 'zaibatsu',  before = [[vim.opt.background = "dark"]] },
      { name = 'zellner',   colorscheme = 'zellner',   before = [[vim.opt.background = "dark"]] },
    },
    livePreview = true,
  },
}
