[colors]
foreground = "#f8efd8"
background = "#053230"
cursor_fg = "#0f3b3a"
cursor_bg = "#f8efd8"
cursor_border = "#f8efd8"
selection_fg = "#f8efd8"
selection_bg = "#969c46"
scrollbar_thumb = "#2d555a"
split = "#f8efd8"

ansi = [
    "#0F3B3A",
    "#D74200",
    "#008000",
    "#CFC041",
    "#0096FF",
    "#DA5BD6",
    "#77BFCF",
    "#c0c0c0",
]

brights = [
    "#155352",
    "#d74200",
    "#00c420",
    "#CFC041",
    "#0086FF",
    "#ff00ff",
    "#00ffff",
    "#ffffff",
]

[colors.tab_bar]
background = "#0f3b3a"

[colors.tab_bar.active_tab]
bg_color = "#063a38"
fg_color = "#f8efd8"

[colors.tab_bar.inactive_tab]
bg_color = "#2d555a"
fg_color = "#f8efd8"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#3b80a1"
fg_color = "#f8efd8"

[colors.tab_bar.new_tab]
bg_color = "#2d555a"
fg_color = "#f8efd8"

[colors.tab_bar.new_tab_hover]
bg_color = "#3b80a1"
fg_color = "#f8efd8"

[metadata]
name = "menguless"
author = "Zekeriya Koc"
origin_url = "https://github.com/zekzekus/dotfiles"
