[colors]
background ='#262626'
foreground= '#c6c6c6'
cursor_fg = '#262626'
cursor_bg = '#c6c6c6'
ansi = [ 
     '#262626',
    '#ac2c2c',
     '#4e9a06',
    '#c4a000',
     '#3465a4',
    '#75507b',
    '#389aad',
    '#626262',
],
  brights = [
     '#767676',
    '#af5f87',
    '#87af87',
    '#d7af5f',
    '#729fcf',
    '#af87d7',
    '#34e2e2',
    '#c6c6c6'
]
[metadata]
aliases = []
name = "Photon"
